network:
  version: 2
  ethernets:
    {{ NIC_NAME }}:
      dhcp4: false
      addresses:
        - {{ STATIC_IPV4_IP }}/24
      gateway4: {{ GATEWAY_IPV4_IP }}  
      nameservers:
        addresses:
          - 1.1.1.1